# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      g++-7

before_install: mkdir -p ~/.R && echo 'CXX11=g++-7' > ~/.R/Makevars

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    before_cache: Rscript -e 'remotes::install_cran(c("pkgdown", "nycflights13", "sessioninfo"))' -e 'remotes::install_github("r-lib/bench")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      skip_cleanup: true
  - r: oldrel
  - r: 3.3
  - r: 3.2
