# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r_github_packages: r-lib/remotes#340

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    before_cache: Rscript -e 'remotes::install_cran(c("pkgdown", "nycflights13", "sessioninfo"))'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      skip_cleanup: true
      on:
        repo: r-lib/vroom
        condition: $TRAVIS_BRANCH = master || -n $TRAVIS_TAG
  - r: oldrel
  - r: 3.3
  - r: 3.2
  - name: "Using C level Connections API"
    r: release
    before_script:
      - mkdir ~/.R
      - echo "CXX11FLAGS+=-DVROOM_USE_CONNECTIONS_API" > ~/.R/Makevars
