# R package
# Test an R package

resources:
  repositories:
    - repository: azuretest
      type: github
      name: jimhester/azuretest
      endpoint: r-lib

jobs:
  - template: azure-tidyverse.yml@azuretest
