name: "vroom"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test-macOS:
    runs-on: macOS-latest
    strategy:
      matrix:
        r: ['3.5.3', '3.6.1']
    steps:
      - uses: actions/checkout@v1
      - name: Setup R
        uses: jimhester/setup-r@master
        with:
          r-version: ${{ matrix.r }}
      - name: Install dependencies
        run: |
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Check package
        run: |
          Rscript -e "install.packages('rcmdcheck')"
          Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual')"
  test-linux:
    env:
      CRAN: 'https://demo.rstudiopm.com/all/__linux__/xenial/latest'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r: ['3.6.1']
    steps:
      - uses: actions/checkout@v1
      - name: Setup R
        uses: jimhester/setup-r@master
        with:
          r-version: ${{ matrix.r }}
      - name: Install dependencies
        run: |
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Check package
        run: |
          Rscript -e "install.packages('rcmdcheck')"
          Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual')"
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup R
        uses: jimhester/setup-r@master
        with:
          r-version: 3.6.1
      - name: Install dependencies
        run: |
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Check package
        run: |
          Rscript -e "install.packages('rcmdcheck')"
          Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual')"
